version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste-node
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:
  # app:
  #   build: .
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: db
  #     DB_USER: root
  #     DB_PASSWORD: root
  #     DB_NAME: root
